---
- name: Download the GitLab repository installation script
  get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh dest=~/gitlab.sh mode=0777

- name: Install the GitLab apt repo
  command: ~/gitlab.sh
  sudo: True

- name: Install GitLab and dependencies
  apt: pkg={{item}} state=installed
  with_items:
    - openssh-server 
    - ca-certificates 
    - postfix 
    - gitlab-ce

- name: Configure and start GitLab
  command: gitlab-ctl reconfigure
  sudo: True
