---
- hosts: all
  sudo: true
  roles:
    - apt-cache-update
    - jdk7

- hosts: prod
  sudo: true
  roles:
    - tomcat

- hosts: tools
  sudo: true
  roles:
    - gitlab
    - tomcat
    - jenkins
